### PR TITLE
Simplified Example and added an option for plotting full recordings 

### PR DESCRIPTION
**Pull request by fx-lange**
Hi @cvalenzuela,

I know that you merged just some hours ago :)
but while testing to plot full recordings I realised some unnecessary complexity in the examples and also wanted to push the plotting feature.

The update now also allows to go through the recordings in edit mode.

Best,
Felix

### CODE REVIEW

**Comment by cvalenzuela** [comment]
Nice, thanks again @fx-lange!

We should probably also update the `README.md` to be more descriptive about this changes and what the examples allow to do. Do you want to write those descriptions? Happy to write them myself if you can't

**Comment by fx-lange** [comment]
Sure, I'll add a draft hopefully today.

**Comment by fx-lange** [comment]
10 instead of 1 day ...

but I also upgraded RecordAndPlay again (last time, I promise) as the previous version would throw errors when actually building your project!

I actually only added one sentence to the readme but also a screenshot. please see this as a draft and feel free to change it to your needs.

happy merging @cvalenzuela

**Comment by cvalenzuela** [comment]
amazing! I just center the image on the README. Everything else looks great!
thanks for this contribution!

**Pull request merged**
